options:
  # 是否启用自动更新 默认关闭
  auto-update: false

  # 注入魔法设置
  infusions:
    # 设置指定类型魔法启用或者禁用
    infusion-destructivecrits: true
    infusion-phantomcrits: true
    infusion-trueaim: true
    infusion-forceful: true
    infusion-volatile: true
    infusion-healing: true
    infusion-autoreplant: true
    infusion-totemstorage: true
    infusion-knockback: true

  # 元素转化选项
  transmutations:
    # 开启或关闭指定的元素转化
    # 强化合金锭
    reinforced-transmutation: true
    # 硬化金属
    hardened-transmutation: true
    # 钢锭
    steel-transmutation: true
    # 大马士革钢锭
    damascus-transmutation: true
    # 压缩碳
    compressed-carbon-transmutation: true
    # 是否使用相同的custom model data（用于自定义材质包）
    # true 直接使用粘液科技原版（指的是插件原版）对应物品的 model data
    # false AlchimiaVitae model data
    use-same-custommodeldata: true

  # 自定义药水效果和强度
  potions:
    # 仁慈酿造
    benevolent-brew:
      # 自定义药水效果
      # NOTE: ticks(gt)对应秒的换算方式为：20ticks = 1秒
      # xxx: 指定药水效果
      #   ticks: 指定持续时间（游戏刻）
      #   level: 指定效果等级（1级即为1级而非2级，别问，问就是玩命令玩的）
      #
      # NOTE:
      #   - 抗性提升计算公式：伤害减免量 = level * 20%，因此5级即可免疫伤害
      #   - 其它详见Minecraft Wiki
      resistance:
        ticks: 6000
        level: 1
      haste:
        ticks: 6000
        level: 2
      regen:
        ticks: 6000
        level: 2
      speed:
        ticks: 6000
        level: 2
      jump:
        ticks: 6000
        level: 2

      # 自定义药水的伤害吸收数值（虽然有小数位，但格式为：0.0 1.0 2.0 ... 以此类推，对应的是血量值（2血量 = 1颗心）
      absorption-halfhearts: 6.0
    # 恶毒混合物（喷溅型药水）
    malevolent-concoction:
      # 自定义药水效果
      weakness:
        ticks: 6000
        level: 3
      slowness:
        ticks: 3000
        level: 2
      poison:
        ticks: 600
        level: 2
      blindness:
        ticks: 1200
        level: 1
      hunger:
        ticks: 600
        level: 2